import { Platform, StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  promptTemplates: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 9,
    marginBottom: 8,
  },
  promptTemplateChip: {
    minHeight: 29,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 9,
    backgroundColor: "#151120",
    paddingHorizontal: 9,
  },
  promptTemplateText: {
    color: "#A78BFA",
    fontSize: 8,
    fontWeight: "700",
  },
  libraryScreen: {
    gap: 13,
    paddingBottom: 24,
  },
  libraryHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
  },
  libraryHeaderMobile: {
    alignItems: "flex-start",
  },
  libraryIntro: {
    flex: 1,
  },
  libraryRefresh: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 13,
    backgroundColor: "#17131F",
    paddingHorizontal: 13,
  },
  libraryRefreshText: {
    color: "#A78BFA",
    fontSize: 12,
    fontWeight: "800",
  },
  librarySearch: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#262033",
    borderRadius: 14,
    backgroundColor: "#17131F",
    paddingHorizontal: 13,
  },
  librarySearchInput: {
    flex: 1,
    minWidth: 0,
    color: "#E9E4F4",
    fontSize: 14,
    paddingVertical: 0,
  },
  libraryCount: {
    color: "#8C88A1",
    fontSize: 11,
    fontWeight: "800",
  },
  libraryList: {
    gap: 10,
  },
  libraryCard: {
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 15,
    backgroundColor: "#17131F",
    padding: 13,
  },
  libraryCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  libraryCardTopMobile: {
    flexWrap: "wrap",
  },
  libraryCardIcon: {
    width: 37,
    height: 37,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#1F1A30",
  },
  libraryCardCopy: {
    flex: 1,
    minWidth: 180,
  },
  libraryCardDate: {
    color: "#8C88A1",
    fontSize: 11,
    fontWeight: "600",
  },
  libraryPrompt: {
    color: "#F4F1FA",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "700",
    marginTop: 5,
  },
  libraryStatus: {
    minHeight: 29,
    justifyContent: "center",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  libraryStatusCompleted: {
    backgroundColor: "#122419",
  },
  libraryStatusFailed: {
    backgroundColor: "#2B1619",
  },
  libraryStatusActive: {
    backgroundColor: "#2B2214",
  },
  libraryStatusText: {
    color: "#8C88A1",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  libraryJobError: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    borderRadius: 9,
    backgroundColor: "#2B1619",
    padding: 9,
    marginTop: 10,
  },
  libraryJobErrorText: {
    flex: 1,
    color: "#F87171",
    fontSize: 12,
    lineHeight: 18,
  },
  libraryVideo: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: "#262033",
    borderRadius: 13,
    backgroundColor: "#14101C",
    paddingHorizontal: 12,
    marginTop: 9,
  },
  libraryVideoIcon: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#7C5CFF",
  },
  libraryVideoCopy: {
    flex: 1,
  },
  libraryVideoName: {
    color: "#E9E4F4",
    fontSize: 12,
    fontWeight: "800",
  },
  libraryVideoHint: {
    color: "#8C88A1",
    fontSize: 10,
    marginTop: 3,
  },
  libraryActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-end",
    marginTop: 9,
  },
  libraryVariantButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 12,
    paddingHorizontal: 12,
  },
  libraryVariantText: {
    color: "#A78BFA",
    fontSize: 11,
    fontWeight: "800",
  },
  libraryEmpty: {
    minHeight: 215,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 16,
    backgroundColor: "#17131F",
    padding: 22,
  },
  libraryEmptyIcon: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "#1F1A30",
  },
  libraryEmptyTitle: {
    color: "#F4F1FA",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 11,
  },
  libraryEmptyText: {
    maxWidth: 350,
    color: "#9894AE",
    fontSize: 12,
    lineHeight: 19,
    textAlign: "center",
    marginTop: 5,
  },
  libraryCreateButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 13,
    backgroundColor: "#7C5CFF",
    paddingHorizontal: 15,
    marginTop: 13,
  },
  libraryCreateText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  videoModalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(24, 22, 35, 0.72)",
    padding: 16,
  },
  videoModalCard: {
    width: "100%",
    maxWidth: 880,
    maxHeight: "100%",
    borderRadius: 18,
    backgroundColor: "#17131F",
    padding: 16,
  },
  videoModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  videoModalTitleCopy: {
    flex: 1,
  },
  videoModalEyebrow: {
    color: "#8C88A1",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  videoModalTitle: {
    color: "#F4F1FA",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 4,
  },
  videoPlayerView: {
    width: "100%",
    aspectRatio: 16 / 9,
    maxHeight: 480,
    overflow: "hidden",
    borderRadius: 12,
    backgroundColor: "#171622",
  },
  videoPromptLabel: {
    color: "#8C88A1",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.8,
    marginTop: 13,
  },
  videoPromptSummary: {
    color: "#C6C1D8",
    fontSize: 9,
    lineHeight: 15,
    marginTop: 5,
  },
  videoModalActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 13,
  },
  videoDownloadButton: {
    minHeight: 37,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 10,
    backgroundColor: "#7C5CFF",
    paddingHorizontal: 12,
  },
  videoDownloadText: {
    color: "#FFFFFF",
    fontSize: 8,
    fontWeight: "800",
  },
  videoVariantButton: {
    minHeight: 37,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 10,
    backgroundColor: "#151120",
    paddingHorizontal: 12,
  },
  videoVariantText: {
    color: "#A78BFA",
    fontSize: 8,
    fontWeight: "800",
  },
  generationOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(18, 16, 29, 0.72)",
    padding: 18,
  },
  generationCard: {
    width: "100%",
    maxWidth: 540,
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 22,
    backgroundColor: "#17131F",
    padding: 20,
    shadowColor: "#120F20",
    shadowOpacity: 0.25,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
    elevation: 12,
  },
  generationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  generationBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  generationLogo: {
    width: 39,
    height: 39,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#7C5CFF",
  },
  generationEyebrow: {
    color: "#8C88A1",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 1,
  },
  generationTitle: {
    color: "#E9E4F4",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 4,
  },
  generationLive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 20,
    backgroundColor: "#122419",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  generationLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#34D399",
  },
  generationLiveText: {
    color: "#398767",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  generationArtwork: {
    height: 150,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 16,
    backgroundColor: "#262239",
    marginTop: 17,
  },
  generationOrbitOuter: {
    position: "absolute",
    width: 132,
    height: 132,
    borderWidth: 1,
    borderColor: "rgba(201, 186, 255, 0.20)",
    borderRadius: 66,
  },
  generationOrbitInner: {
    position: "absolute",
    width: 88,
    height: 88,
    borderWidth: 1,
    borderColor: "rgba(201, 186, 255, 0.28)",
    borderRadius: 44,
  },
  generationCore: {
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#554783",
  },
  generationNode: {
    position: "absolute",
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.16)",
    borderRadius: 11,
    backgroundColor: "#343047",
  },
  generationNodeA: {
    top: 27,
    left: "30%",
  },
  generationNodeB: {
    right: "29%",
    bottom: 26,
  },
  generationStatusRow: {
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  generationStatus: {
    flex: 1,
    color: "#49465A",
    fontSize: 9,
    fontWeight: "700",
  },
  generationTimer: {
    color: "#6C53CE",
    fontSize: 10,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  generationTerminal: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#353344",
    borderRadius: 13,
    backgroundColor: "#1E1D29",
  },
  terminalTopbar: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#353344",
    paddingHorizontal: 10,
  },
  terminalLights: {
    flexDirection: "row",
    gap: 4,
    marginRight: 9,
  },
  terminalLight: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  terminalCaption: {
    flex: 1,
    color: "#AAA7B7",
    fontSize: 7,
    fontWeight: "600",
  },
  terminalLive: {
    color: "#68C7A1",
    fontSize: 6,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  terminalLines: {
    gap: 7,
    paddingHorizontal: 11,
    paddingVertical: 11,
  },
  terminalLine: {
    color: "#D4D1DF",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 8,
    lineHeight: 12,
  },
  terminalPrompt: {
    color: "#C6ABFF",
    fontWeight: "800",
  },
  terminalSuccess: {
    color: "#64C59D",
    fontWeight: "800",
  },
  terminalInfo: {
    color: "#E7BC68",
    fontWeight: "800",
  },
  generationFootnote: {
    color: "#8C88A1",
    fontSize: 8,
    lineHeight: 13,
    textAlign: "center",
    marginTop: 11,
  },
  contentIdeaCard: {
    gap: 11,
    borderWidth: 1,
    borderColor: "#4A3A1E",
    borderRadius: 16,
    backgroundColor: "#241C10",
    padding: 14,
    marginTop: 13,
  },
  contentIdeaHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  contentIdeaIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#3A2E18",
  },
  contentIdeaCopy: {
    flex: 1,
  },
  contentIdeaTitle: {
    color: "#F4F1FA",
    fontSize: 14,
    fontWeight: "800",
  },
  contentIdeaSubtitle: {
    color: "#9894AE",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 3,
  },
  contentIdeaLabel: {
    color: "#8C8997",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.55,
    marginTop: 2,
  },
  industryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
  },
  industryChip: {
    minHeight: 38,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#EBE7EF",
    borderRadius: 12,
    backgroundColor: "#17131F",
    paddingHorizontal: 11,
  },
  industryChipActive: {
    borderColor: "#D9CBFF",
    backgroundColor: "#F2EEFF",
  },
  industryChipText: {
    color: "#777483",
    fontSize: 11,
    fontWeight: "700",
  },
  industryChipTextActive: {
    color: "#A78BFA",
    fontWeight: "800",
  },
  contentIdeaFields: {
    gap: 6,
  },
  contentIdeaInput: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: "#ECE8EF",
    borderRadius: 12,
    backgroundColor: "#17131F",
    color: "#E9E4F4",
    fontSize: 14,
    paddingHorizontal: 12,
  },
  contentIdeaButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "#E7DDF5",
    borderRadius: 12,
    backgroundColor: "#F6F1FF",
  },
  contentIdeaButtonText: {
    color: "#A78BFA",
    fontSize: 12,
    fontWeight: "800",
  },
  studioTaskPanel: {
    gap: 11,
    paddingHorizontal: 14,
    paddingVertical: 15,
  },
  publisherPanel: {
    gap: 11,
    paddingHorizontal: 14,
    paddingVertical: 15,
  },
  publisherPlatformRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  publisherPlatform: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#E7E4EE",
    borderRadius: 10,
    backgroundColor: "#17131F",
    paddingHorizontal: 10,
  },
  publisherPlatformActive: {
    borderColor: "#D9D0F7",
    backgroundColor: "#F5F1FF",
  },
  publisherPlatformText: {
    color: "#8C88A1",
    fontSize: 11,
    fontWeight: "700",
  },
  publisherPlatformTextActive: {
    color: "#A78BFA",
  },
  publisherStartButton: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 10,
    backgroundColor: "#7C5CFF",
    paddingHorizontal: 12,
  },
  publisherStartText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
  },
  publisherToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 11,
    backgroundColor: "#17131F",
    padding: 6,
  },
  publisherUrl: {
    flex: 1,
    color: "#8C88A1",
    fontSize: 9,
  },
  publisherToolbarButton: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 8,
    backgroundColor: "#F3F0FC",
    paddingHorizontal: 9,
  },
  publisherToolbarText: {
    color: "#A78BFA",
    fontSize: 10,
    fontWeight: "800",
  },
  publisherStopButton: {
    backgroundColor: "#2B1619",
  },
  publisherUploadNotice: {
    color: "#34D399",
    fontSize: 10,
    fontWeight: "700",
  },
  publisherFrame: {
    width: "100%",
    aspectRatio: 1.6,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#D9D5E3",
    borderRadius: 11,
    backgroundColor: "#ECEAF1",
  },
  publisherFrameLoading: {
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  publisherFrameImage: {
    width: "100%",
    height: "100%",
  },
  publisherFrameText: {
    color: "#8C8998",
    fontSize: 9,
  },
  publisherControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  publisherTypingInput: {
    flex: 1,
    minHeight: 36,
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 9,
    backgroundColor: "#17131F",
    color: "#F4F1FA",
    fontSize: 11,
    paddingHorizontal: 9,
  },
  studioTaskHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  studioTaskIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#1F1A30",
  },
  studioTaskHeadingCopy: {
    flex: 1,
  },
  studioTaskEyebrow: {
    color: "#918D9D",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  studioTaskTitle: {
    color: "#F4F1FA",
    fontSize: 15,
    fontWeight: "800",
    marginTop: 3,
  },
  studioTaskDescription: {
    color: "#9894AE",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  studioLimitation: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    borderRadius: 10,
    backgroundColor: "#FFF8EA",
    padding: 9,
  },
  studioLimitationText: {
    flex: 1,
    color: "#7D6843",
    fontSize: 11,
    lineHeight: 17,
  },
  mediaInputPanel: {
    gap: 9,
    borderWidth: 1,
    borderColor: "#E8E3F6",
    borderRadius: 13,
    backgroundColor: "#161220",
    padding: 10,
  },
  mediaPickButton: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 10,
    backgroundColor: "#1F1A30",
  },
  mediaPickButtonText: {
    color: "#A78BFA",
    fontSize: 12,
    fontWeight: "800",
  },
  mediaSelectionCount: {
    color: "#9894AE",
    fontSize: 11,
    textAlign: "center",
  },
  mediaPresetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  mediaPresetChip: {
    borderWidth: 1,
    borderColor: "#E2DEED",
    borderRadius: 999,
    backgroundColor: "#17131F",
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  mediaPresetChipActive: {
    borderColor: "#7C5CFF",
    backgroundColor: "#1F1A30",
  },
  mediaPresetText: {
    color: "#8C88A1",
    fontSize: 11,
    fontWeight: "700",
  },
  mediaPresetTextActive: {
    color: "#A78BFA",
  },
  mediaThumbRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mediaThumb: {
    width: 58,
    height: 58,
    borderRadius: 10,
    backgroundColor: "#E9E6F2",
  },
  studioBriefInput: {
    minHeight: 136,
    maxHeight: 220,
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 14,
    backgroundColor: "#17131F",
    color: "#F4F1FA",
    fontSize: 14,
    lineHeight: 21,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  studioRunButton: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 10,
    backgroundColor: "#7C5CFF",
  },
  studioRunText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "800",
  },
  studioResultCard: {
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 12,
    backgroundColor: "#14101C",
    padding: 11,
  },
  museMediaGallery: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 12,
    backgroundColor: "#14101C",
    padding: 11,
    gap: 10,
  },
  museMediaGalleryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  museMediaHeading: {
    color: "#6550AE",
    fontSize: 12,
    fontWeight: "800",
  },
  museMediaSubheading: {
    color: "#918D9E",
    fontSize: 10,
    marginTop: 3,
  },
  museMediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  museMediaItem: {
    flexGrow: 1,
    flexBasis: 210,
    maxWidth: 360,
    borderWidth: 1,
    borderColor: "#EEEAF6",
    borderRadius: 12,
    backgroundColor: "#17131F",
    padding: 7,
  },
  museMediaImageButton: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    height: 220,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#0B0912",
  },
  museMediaThumbnail: {
    width: "100%",
    height: "100%",
  },
  museMediaResolution: {
    position: "absolute",
    left: 7,
    bottom: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 7,
    backgroundColor: "rgba(4, 2, 8, 0.82)",
  },
  museMediaResolutionText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
  },
  museMediaZoom: {
    position: "absolute",
    right: 7,
    bottom: 7,
    width: 27,
    height: 27,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "rgba(4, 2, 8, 0.82)",
  },
  museMediaName: {
    color: "#716D80",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 7,
  },
  museImageLightbox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(14, 12, 22, 0.96)",
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  museImageLightboxToolbar: {
    width: "100%",
    maxWidth: 1200,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  museImageLightboxTitle: {
    flex: 1,
  },
  museImageLightboxName: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  museImageLightboxDimensions: {
    color: "#C8C3D3",
    fontSize: 11,
    marginTop: 3,
  },
  museImageLightboxClose: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
  },
  museImageLightboxImage: {
    flex: 1,
    width: "100%",
    maxWidth: 1200,
    minHeight: 0,
  },
  museImageLightboxSave: {
    minWidth: 180,
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 11,
    backgroundColor: "#7C5CFF",
    marginTop: 14,
  },
  studioResultHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 8,
  },
  studioResultIcon: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "#1F1A30",
  },
  studioResultTitle: {
    color: "#55477F",
    fontSize: 8,
    fontWeight: "900",
  },
  studioResultText: {
    color: "#4F4C5D",
    fontSize: 9,
    lineHeight: 16,
  },
  studioImagePreview: {
    width: "100%",
    aspectRatio: 4 / 5,
    borderRadius: 10,
    backgroundColor: "#1F1A30",
    marginTop: 10,
  },
  mediaSaveButton: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 10,
    backgroundColor: "#7C5CFF",
    marginTop: 9,
  },
  mediaSaveButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  loadingSparkle: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#1F1A30",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#0B0912",
  },
  app: {
    flex: 1,
    flexDirection: "row",
  },
  appMobile: {
    flexDirection: "column",
  },
  sidebar: {
    width: 270,
    backgroundColor: "#12101A",
    borderRightWidth: 1,
    borderRightColor: "#2B2539",
    paddingHorizontal: 21,
    paddingTop: 29,
    paddingBottom: 20,
  },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  brandMark: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#7C5CFF",
  },
  brandText: {
    color: "#272638",
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  brandAI: {
    alignSelf: "flex-start",
    color: "#7658F6",
    fontSize: 10,
    fontWeight: "900",
    marginLeft: -6,
    marginTop: 4,
  },
  sidebarSection: {
    color: "#9894AE",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.1,
    marginTop: 43,
    marginBottom: 12,
    paddingHorizontal: 9,
  },
  sidebarNavigation: {
    gap: 5,
  },
  navItem: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 11,
    paddingHorizontal: 12,
    position: "relative",
  },
  navItemActive: {
    backgroundColor: "#EEE8FF",
  },
  navItemPressed: {
    opacity: 0.76,
  },
  navLabel: {
    color: "#8C88A1",
    fontSize: 13,
    fontWeight: "600",
  },
  navLabelActive: {
    color: "#6549D7",
    fontWeight: "700",
  },
  navIndicator: {
    position: "absolute",
    right: 0,
    width: 3,
    height: 20,
    borderTopLeftRadius: 3,
    borderBottomLeftRadius: 3,
    backgroundColor: "#7C5CFF",
  },
  sidebarDivider: {
    height: 1,
    backgroundColor: "#EDE8F3",
    marginVertical: 17,
  },
  sidebarBottom: {
    flex: 1,
    justifyContent: "flex-end",
    gap: 17,
  },
  sidePlanCard: {
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 15,
    backgroundColor: "#1E1930",
    padding: 14,
  },
  planIcon: {
    width: 29,
    height: 29,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#EFEBFF",
    marginBottom: 11,
  },
  planTitle: {
    color: "#333147",
    fontSize: 12,
    fontWeight: "700",
  },
  planBody: {
    color: "#8E8B9C",
    fontSize: 10,
    lineHeight: 15,
    marginTop: 5,
  },
  planStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 12,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#5BB793",
  },
  planStatusText: {
    color: "#8C88A1",
    fontSize: 9,
    fontWeight: "600",
  },
  version: {
    color: "#AAA8B5",
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 0.6,
    textAlign: "center",
  },
  main: {
    flex: 1,
    minWidth: 0,
  },
  mobileHeader: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1A1526",
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#EAE5F1",
  },
  mobileHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  mobileStudioBadge: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#EAE5FA",
    borderRadius: 12,
    backgroundColor: "#F4F0FF",
    paddingHorizontal: 10,
  },
  mobileStudioBadgeText: {
    color: "#6650B6",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  headerIconButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 11,
    backgroundColor: "#17131F",
  },
  scroll: {
    flex: 1,
  },
  content: {
    width: "100%",
    maxWidth: 1400,
    alignSelf: "center",
    paddingHorizontal: 42,
    paddingTop: 32,
    paddingBottom: 46,
  },
  contentDesktop: {
    paddingHorizontal: 54,
    paddingTop: 30,
  },
  contentMobile: {
    paddingHorizontal: 16,
    paddingTop: 17,
    paddingBottom: 28,
  },
  topbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  topbarEyebrow: {
    color: "#9593A1",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.15,
  },
  topbarTitle: {
    color: "#2D2B3D",
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginTop: 4,
  },
  topbarRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  topbarStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 20,
    backgroundColor: "#1A1526",
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  topbarStatusText: {
    color: "#8C88A1",
    fontSize: 10,
    fontWeight: "600",
  },
  avatar: {
    width: 35,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#EBE6FF",
  },
  avatarText: {
    color: "#684BDE",
    fontSize: 10,
    fontWeight: "800",
  },
  hero: {
    minHeight: 374,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 28,
    backgroundColor: "#211A35",
    paddingVertical: 48,
    paddingHorizontal: 54,
    position: "relative",
    boxShadow: "0px 24px 56px rgba(0, 0, 0, 0.24)",
  },
  heroMobile: {
    minHeight: 364,
    alignItems: "flex-start",
    borderRadius: 28,
    paddingVertical: 25,
    paddingHorizontal: 21,
    boxShadow: "0px 18px 40px rgba(0, 0, 0, 0.23)",
  },
  heroGlowOne: {
    position: "absolute",
    width: 450,
    height: 450,
    borderRadius: 225,
    backgroundColor: "rgba(126, 82, 237, 0.32)",
    right: -38,
    top: -205,
  },
  heroGlowTwo: {
    position: "absolute",
    width: 290,
    height: 290,
    borderRadius: 145,
    backgroundColor: "rgba(0, 0, 0, 0.16)",
    right: 255,
    bottom: -238,
  },
  heroCopy: {
    zIndex: 2,
    maxWidth: 570,
  },
  heroCopyMobile: {
    width: "100%",
    flexShrink: 1,
  },
  heroPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.24)",
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.08)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 21,
  },
  heroPillMobile: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    marginBottom: 18,
  },
  heroPillText: {
    color: "#E1D7FA",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  heroPillTextMobile: {
    fontSize: 9,
    letterSpacing: 0.75,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 48,
    lineHeight: 56,
    fontWeight: "800",
    letterSpacing: -1.7,
  },
  heroTitleMobile: {
    fontSize: 34,
    lineHeight: 41,
    letterSpacing: -1.15,
  },
  heroTitleAccent: {
    color: "#C6B1FF",
  },
  heroDescription: {
    maxWidth: 450,
    color: "#D0C9DC",
    fontSize: 15,
    lineHeight: 24,
    marginTop: 15,
  },
  heroDescriptionMobile: {
    maxWidth: 310,
    color: "#D0C9DC",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 12,
  },
  heroActions: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 11,
    marginTop: 24,
  },
  heroProofRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 19,
  },
  heroProofIcons: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 2,
  },
  heroProofIcon: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#211A35",
    borderRadius: 10,
    marginLeft: -3,
  },
  heroProofIconImage: {
    backgroundColor: "#7C5CFF",
  },
  heroProofIconVideo: {
    backgroundColor: "#D18B34",
  },
  heroProofIconSparkle: {
    backgroundColor: "#31977D",
  },
  heroProofText: {
    color: "#C8BEDB",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.55,
  },
  primaryButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: "#F1EBFF",
    paddingHorizontal: 17,
  },
  primaryButtonMobile: {
    minHeight: 49,
    borderRadius: 14,
    paddingHorizontal: 15,
  },
  primaryButtonText: {
    color: "#34274F",
    fontSize: 13,
    fontWeight: "800",
  },
  primaryButtonTextMobile: {
    fontSize: 13,
  },
  secondaryButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(234, 226, 255, 0.30)",
    borderRadius: 14,
    backgroundColor: "rgba(0, 0, 0, 0.075)",
    paddingHorizontal: 17,
  },
  secondaryButtonMobile: {
    minHeight: 49,
    borderRadius: 14,
    paddingHorizontal: 15,
  },
  secondaryButtonText: {
    color: "#F3EFFB",
    fontSize: 13,
    fontWeight: "700",
  },
  secondaryButtonTextMobile: {
    fontSize: 13,
  },
  buttonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  heroIndex: {
    position: "absolute",
    right: 30,
    bottom: 24,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  heroIndexNumber: {
    color: "#D5C6FF",
    fontSize: 11,
    fontWeight: "800",
  },
  heroIndexLine: {
    width: 40,
    height: 1,
    backgroundColor: "rgba(220, 207, 255, 0.38)",
  },
  heroIndexLabel: {
    color: "#B9AECF",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1,
  },
  heroArtwork: {
    position: "absolute",
    width: 330,
    height: 330,
    right: 78,
    top: 22,
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
  },
  artCircleOuter: {
    position: "absolute",
    width: 292,
    height: 292,
    borderRadius: 146,
    borderWidth: 1,
    borderColor: "rgba(230, 217, 255, 0.14)",
  },
  artCircleMiddle: {
    position: "absolute",
    width: 226,
    height: 226,
    borderRadius: 113,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.23)",
  },
  artCircleInner: {
    position: "absolute",
    width: 158,
    height: 158,
    borderRadius: 79,
    borderWidth: 1,
    borderColor: "rgba(230, 217, 255, 0.34)",
  },
  artSparkle: {
    width: 94,
    height: 94,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 31,
    backgroundColor: "#17131F",
    transform: [{ rotate: "-8deg" }],
  },
  artBadge: {
    position: "absolute",
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17,
    backgroundColor: "#17131F",
    boxShadow: "0px 8px 22px rgba(0, 0, 0, 0.16)",
  },
  artBadgeImage: {
    left: 28,
    top: 57,
  },
  artBadgeVideo: {
    right: 22,
    top: 99,
  },
  artBadgeAudio: {
    left: 73,
    bottom: 18,
  },
  artStar: {
    position: "absolute",
    top: 45,
    right: 65,
  },
  welcomeRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 42,
    marginBottom: 19,
  },
  welcomeRowMobile: {
    marginTop: 30,
    marginBottom: 17,
  },
  sectionEyebrow: {
    color: "#918F9E",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.15,
  },
  sectionHeading: {
    color: "#F4F1FA",
    fontSize: 26,
    lineHeight: 32,
    fontWeight: "800",
    letterSpacing: -0.45,
    marginTop: 7,
  },
  sectionHeadingMobile: {
    fontSize: 23,
    lineHeight: 29,
    letterSpacing: -0.55,
  },
  sectionSubheading: {
    color: "#8C88A1",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
  },
  sectionSubheadingMobile: {
    fontSize: 13,
    lineHeight: 19,
  },
  toolCount: {
    color: "#9894AE",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
    paddingBottom: 4,
  },
  quickGrid: {
    flexDirection: "row",
    gap: 16,
  },
  quickGridMobile: {
    flexDirection: "row",
    gap: 10,
  },
  quickCard: {
    flex: 1,
    minHeight: 100,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderWidth: 1,
    borderColor: "#E9E6F0",
    borderRadius: 21,
    backgroundColor: "#17131F",
    paddingHorizontal: 19,
    paddingVertical: 18,
    boxShadow: "0px 10px 26px rgba(0, 0, 0, 0.07)",
  },
  quickCardMobile: {
    minHeight: 142,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    borderRadius: 21,
    padding: 15,
    boxShadow: "0px 9px 24px rgba(0, 0, 0, 0.085)",
  },
  quickImageCard: {
    borderColor: "#7C5CFF",
    backgroundColor: "#7C5CFF",
    boxShadow: "0px 12px 28px rgba(0, 0, 0, 0.22)",
  },
  quickVideoCard: {
    borderColor: "#4A3A1E",
    backgroundColor: "#241C10",
  },
  quickExploreCard: {
    borderColor: "#1E4030",
    backgroundColor: "#0F1F18",
  },
  quickImageTitle: {
    color: "#FFFFFF",
  },
  quickImageSubtitle: {
    color: "#E0D8FF",
  },
  cardPressed: {
    opacity: 0.76,
  },
  quickIcon: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    flexShrink: 0,
  },
  quickArrow: {
    width: 29,
    height: 29,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "#141017",
  },
  quickArrowMobile: {
    position: "absolute",
    right: 13,
    top: 13,
    backgroundColor: "#17131F",
  },
  quickCopy: {
    flex: 1,
    minWidth: 0,
  },
  quickTitle: {
    color: "#F4F1FA",
    fontSize: 15,
    fontWeight: "800",
  },
  quickCardMobileTitle: {
    fontSize: 14,
    lineHeight: 19,
  },
  quickSubtitle: {
    color: "#8C88A1",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 5,
  },
  quickCardMobileSubtitle: {
    fontSize: 11,
    lineHeight: 16,
  },
  toolSection: {
    marginTop: 44,
  },
  toolSectionHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 20,
    marginBottom: 18,
  },
  toolSectionHeaderMobile: {
    alignItems: "stretch",
    flexDirection: "column",
    gap: 13,
    marginBottom: 15,
  },
  searchBox: {
    width: 290,
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 15,
    backgroundColor: "#1A1526",
    paddingHorizontal: 14,
  },
  searchBoxMobile: {
    width: "100%",
    height: 46,
    borderRadius: 14,
    paddingHorizontal: 13,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: "#E9E4F4",
    fontSize: 13,
    paddingVertical: 0,
  },
  searchInputMobile: {
    fontSize: 14,
  },
  categoryList: {
    gap: 9,
    paddingBottom: 17,
  },
  categoryChip: {
    minHeight: 43,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E4DFEA",
    borderRadius: 14,
    backgroundColor: "#1A1526",
    paddingHorizontal: 16,
  },
  categoryChipMobile: {
    minHeight: 42,
    borderRadius: 13,
    paddingHorizontal: 15,
  },
  categoryChipActive: {
    borderColor: "#7C5CFF",
    backgroundColor: "#7C5CFF",
  },
  categoryText: {
    color: "#8C88A1",
    fontSize: 13,
    fontWeight: "700",
  },
  categoryTextMobile: {
    fontSize: 13,
  },
  categoryTextActive: {
    color: "#FFFFFF",
  },
  toolGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  toolCard: {
    width: "100%",
    minHeight: 176,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 15,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.16)",
    borderTopWidth: 3,
    borderRadius: 22,
    backgroundColor: "#1F1A30",
    paddingHorizontal: 19,
    paddingVertical: 19,
    position: "relative",
    boxShadow: "0px 12px 28px rgba(0, 0, 0, 0.09)",
  },
  toolCardMobile: {
    minHeight: 166,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 13,
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 16,
    position: "relative",
  },
  toolCardHalf: {
    width: "48%",
  },
  toolCardThird: {
    width: "30.5%",
  },
  toolIcon: {
    width: 50,
    height: 50,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
  },
  toolIconMobile: {
    width: 48,
    height: 48,
    borderRadius: 16,
  },
  toolCopy: {
    width: "100%",
    minWidth: 0,
  },
  toolCopyMobile: {
    width: "100%",
    paddingRight: 5,
  },
  toolTitleLine: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  toolTitle: {
    color: "#333246",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  toolTitleMobile: {
    fontSize: 14,
    lineHeight: 19,
  },
  toolStatus: {
    overflow: "hidden",
    borderRadius: 4,
    backgroundColor: "#1F1A30",
    color: "#7454E7",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.25,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  toolStatusSoon: {
    backgroundColor: "#FFF4E4",
    color: "#B77625",
  },
  toolDescription: {
    color: "#8C88A1",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
  },
  toolDescriptionMobile: {
    fontSize: 11,
    lineHeight: 16,
    marginTop: 6,
  },
  toolArrowMobile: {
    position: "absolute",
    right: 13,
    top: 13,
  },
  toolArrow: {
    position: "absolute",
    right: 13,
    top: 13,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#141017",
  },
  noResults: {
    width: "100%",
    minHeight: 150,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 14,
    backgroundColor: "#17131F",
    gap: 7,
  },
  noResultsTitle: {
    color: "#F4F1FA",
    fontSize: 12,
    fontWeight: "700",
  },
  noResultsText: {
    color: "#8C88A1",
    fontSize: 10,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingTop: 24,
    paddingBottom: 9,
  },
  footerText: {
    color: "#9997A5",
    fontSize: 9,
  },
  bottomBar: {
    minHeight: 77,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: "#E7E0EF",
    backgroundColor: "#1A1526",
    paddingHorizontal: 5,
    paddingTop: 7,
    paddingBottom: Platform.OS === "ios" ? 9 : 7,
  },
  bottomItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 59,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    borderRadius: 14,
    paddingVertical: 4,
  },
  bottomItemPressed: {
    opacity: 0.72,
  },
  bottomIconWrap: {
    minWidth: 42,
    minHeight: 31,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
  },
  bottomIconWrapActive: {
    backgroundColor: "#1F1A30",
  },
  bottomLabel: {
    color: "#93919F",
    fontSize: 10,
    fontWeight: "600",
  },
  bottomLabelActive: {
    color: "#A78BFA",
    fontWeight: "800",
  },
  musePage: {
    paddingBottom: 22,
  },
  musePageIntro: {
    marginBottom: 20,
  },
  authCard: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 19,
    backgroundColor: "#17131F",
    padding: 23,
    marginTop: 12,
  },
  authIllustration: {
    width: 62,
    height: 62,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "#1F1A30",
    marginBottom: 17,
  },
  authIllustrationTile: {
    width: 43,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: "#17131F",
  },
  authIllustrationSpark: {
    position: "absolute",
    right: 6,
    top: 5,
  },
  authTitle: {
    color: "#F4F1FA",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  authDescription: {
    color: "#9894AE",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  formLabel: {
    color: "#8C88A1",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.75,
    marginTop: 15,
    marginBottom: 7,
  },
  formInput: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#E8E7ED",
    borderRadius: 14,
    backgroundColor: "#17131F",
    color: "#F4F1FA",
    fontSize: 15,
    paddingHorizontal: 14,
  },
  bridgeHelp: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderRadius: 10,
    backgroundColor: "#FFF8EC",
    padding: 10,
    marginTop: 12,
  },
  bridgeHelpText: {
    flex: 1,
    color: "#795E37",
    fontSize: 12,
    lineHeight: 19,
  },
  codeInline: {
    color: "#59438F",
    fontWeight: "800",
  },
  authButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderRadius: 14,
    backgroundColor: "#7C5CFF",
    marginTop: 14,
  },
  disabledButton: {
    opacity: 0.48,
  },
  authButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  changeEmailButton: {
    alignSelf: "center",
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 12,
    marginTop: 2,
  },
  changeEmailText: {
    color: "#7254E8",
    fontSize: 12,
    fontWeight: "700",
  },
  privacyLine: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 7,
    marginTop: 15,
  },
  privacyText: {
    flex: 1,
    color: "#8C88A1",
    fontSize: 11,
    lineHeight: 17,
  },
  museWorkspace: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E9E5F1",
    borderRadius: 20,
    backgroundColor: "#17131F",
    boxShadow: "0px 12px 34px rgba(0, 0, 0, 0.075)",
  },
  museWorkspaceHeader: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
  },
  museIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  museIdentityIcon: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#7C5CFF",
  },
  museIdentityTitle: {
    color: "#F4F1FA",
    fontSize: 15,
    fontWeight: "800",
  },
  museOnlineLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 4,
  },
  museOnlineText: {
    color: "#8C88A1",
    fontSize: 11,
  },
  iconAction: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 13,
  },
  museTabs: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderTopWidth: 1,
    borderTopColor: "#F0EFF3",
    borderBottomWidth: 1,
    borderBottomColor: "#2B2539",
    backgroundColor: "#F8F7FB",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  museTab: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 11,
    backgroundColor: "transparent",
    paddingHorizontal: 12,
  },
  museTabActive: {
    backgroundColor: "#221B3A",
  },
  museTabText: {
    color: "#8D8B99",
    fontSize: 12,
    fontWeight: "600",
  },
  museTabTextActive: {
    color: "#A78BFA",
    fontWeight: "800",
  },
  chatPanel: {
    paddingHorizontal: 16,
    paddingTop: 17,
    paddingBottom: 18,
  },
  chatTranscript: {
    minHeight: 300,
    maxHeight: 500,
  },
  chatTranscriptContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingVertical: 13,
    gap: 12,
  },
  messageRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 7,
  },
  messageRowUser: {
    justifyContent: "flex-end",
  },
  messageAvatar: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#1F1A30",
  },
  messageBubble: {
    maxWidth: "83%",
    borderRadius: 13,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  userBubble: {
    borderBottomRightRadius: 4,
    backgroundColor: "#7C5CFF",
  },
  systemBubble: {
    backgroundColor: "#FFF7E9",
  },
  assistantBubble: {
    borderBottomLeftRadius: 4,
    backgroundColor: "#F5F4F8",
  },
  messageText: {
    color: "#4C4A5A",
    fontSize: 14,
    lineHeight: 22,
  },
  userMessageText: {
    color: "#FFFFFF",
  },
  chatWelcome: {
    alignItems: "center",
    paddingVertical: 10,
  },
  chatWelcomeIcon: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "#1F1A30",
  },
  chatWelcomeTitle: {
    color: "#353347",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 11,
  },
  chatWelcomeBody: {
    maxWidth: 420,
    color: "#9894AE",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    marginTop: 5,
  },
  suggestionList: {
    width: "100%",
    gap: 6,
    marginTop: 13,
  },
  suggestionChip: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "#ECEAF3",
    borderRadius: 12,
    backgroundColor: "#17131F",
    paddingHorizontal: 12,
  },
  suggestionText: {
    flex: 1,
    color: "#5E5A70",
    fontSize: 12,
  },
  loadingLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#EEEAF8",
    borderRadius: 12,
    backgroundColor: "#161220",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 5,
  },
  typingDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#8A72E8",
  },
  loadingText: {
    color: "#9894AE",
    fontSize: 12,
    marginLeft: 3,
  },
  chatComposer: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    borderWidth: 1,
    borderColor: "#E7E5EE",
    borderRadius: 16,
    backgroundColor: "#17131F",
    padding: 6,
  },
  chatInput: {
    flex: 1,
    minHeight: 42,
    maxHeight: 120,
    color: "#F4F1FA",
    fontSize: 15,
    lineHeight: 22,
    paddingHorizontal: 9,
    paddingVertical: 10,
  },
  sendButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#7C5CFF",
  },
  composerHint: {
    color: "#9A98A5",
    fontSize: 10,
    lineHeight: 15,
    marginTop: 7,
    paddingHorizontal: 2,
  },
  videoPanel: {
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 15,
  },
  videoIntro: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  videoIntroIcon: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#FFF3E3",
  },
  videoIntroCopy: {
    flex: 1,
  },
  videoIntroTitle: {
    color: "#F4F1FA",
    fontSize: 14,
    fontWeight: "800",
  },
  videoIntroText: {
    color: "#9894AE",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  videoPromptInput: {
    minHeight: 128,
    maxHeight: 220,
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 14,
    backgroundColor: "#17131F",
    color: "#F4F1FA",
    fontSize: 15,
    lineHeight: 22,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  promptHelpRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 7,
  },
  promptHelpText: {
    flex: 1,
    color: "#8C88A1",
    fontSize: 11,
    lineHeight: 17,
  },
  referenceHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 15,
  },
  referenceHint: {
    color: "#8C88A1",
    fontSize: 8,
    marginTop: -4,
  },
  addReferenceButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#332B4A",
    borderRadius: 12,
    backgroundColor: "#151120",
    paddingHorizontal: 11,
  },
  addReferenceText: {
    color: "#A78BFA",
    fontSize: 11,
    fontWeight: "700",
  },
  referenceList: {
    gap: 6,
    marginTop: 9,
  },
  referenceItem: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 9,
    backgroundColor: "#17131F",
    paddingHorizontal: 9,
  },
  referenceName: {
    flex: 1,
    color: "#B7B2C9",
    fontSize: 9,
  },
  dropzone: {
    minHeight: 87,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#DCD7EA",
    borderRadius: 11,
    backgroundColor: "#FBFAFD",
    paddingHorizontal: 8,
    marginTop: 9,
  },
  dropzoneIcon: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "#1F1A30",
  },
  dropzoneTitle: {
    color: "#C6C1D8",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 6,
  },
  dropzoneText: {
    color: "#8C88A1",
    fontSize: 10,
    marginTop: 4,
  },
  jobNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 9,
    backgroundColor: "#F4F2FC",
    padding: 9,
    marginTop: 11,
  },
  jobSpinner: {
    width: 13,
    height: 13,
    borderWidth: 2,
    borderColor: "#DCD5F6",
    borderTopColor: "#7C5CFF",
    borderRadius: 7,
  },
  jobNoticeText: {
    flex: 1,
    color: "#625B7E",
    fontSize: 8,
    lineHeight: 13,
  },
  videoResult: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: "#E8E6EE",
    borderRadius: 10,
    backgroundColor: "#17131F",
    paddingHorizontal: 9,
    marginTop: 8,
  },
  resultIcon: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#7C5CFF",
  },
  resultCopy: {
    flex: 1,
  },
  resultTitle: {
    color: "#454354",
    fontSize: 9,
    fontWeight: "700",
  },
  resultSubtitle: {
    color: "#8C88A1",
    fontSize: 7,
    marginTop: 3,
  },
  generateButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: "#7C5CFF",
    marginTop: 13,
  },
  generateButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  museSupport: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    paddingHorizontal: 4,
    marginTop: 12,
  },
  museSupportText: {
    flex: 1,
    color: "#8C88A1",
    fontSize: 10,
    lineHeight: 16,
  },
  inlineNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    borderRadius: 9,
    padding: 9,
    marginTop: 9,
  },
  errorNotice: {
    backgroundColor: "#2B1619",
  },
  successNotice: {
    backgroundColor: "#ECF7F1",
  },
  inlineNoticeText: {
    flex: 1,
    color: "#38745F",
    fontSize: 12,
    lineHeight: 18,
  },
  errorNoticeText: {
    color: "#F87171",
  },
  settingsScreen: {
    paddingBottom: 25,
  },
  settingsIntro: {
    marginBottom: 19,
  },
  accountSettingsCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 17,
    backgroundColor: "#17131F",
    padding: 13,
    marginBottom: 16,
  },
  accountSettingsIcon: {
    width: 39,
    height: 39,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#1F1A30",
  },
  accountSettingsCopy: {
    flex: 1,
    gap: 3,
  },
  accountSettingsTitle: {
    color: "#F4F1FA",
    fontSize: 13,
    fontWeight: "800",
  },
  accountSettingsEmail: {
    color: "#9894AE",
    fontSize: 12,
  },
  accountLogoutButton: {
    borderRadius: 11,
    backgroundColor: "#F8F5FF",
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  accountLogoutText: {
    color: "#A78BFA",
    fontSize: 12,
    fontWeight: "800",
  },
  adminEntry: {
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#2E2B3D",
    borderRadius: 17,
    backgroundColor: "#242233",
    paddingHorizontal: 15,
    marginTop: 14,
  },
  adminEntryIcon: {
    width: 37,
    height: 37,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#353044",
  },
  adminEntryCopy: {
    flex: 1,
  },
  adminEntryTitle: {
    color: "#F3EBD9",
    fontSize: 14,
    fontWeight: "800",
  },
  adminEntryText: {
    color: "#AAA6B5",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  adminScreen: {
    gap: 15,
    paddingBottom: 26,
  },
  adminHero: {
    minHeight: 183,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
    borderWidth: 1,
    borderColor: "#353044",
    borderRadius: 21,
    backgroundColor: "#211F30",
    paddingHorizontal: 26,
    paddingVertical: 23,
    position: "relative",
  },
  adminHeroMobile: {
    minHeight: 212,
    alignItems: "flex-start",
    flexDirection: "column",
    paddingHorizontal: 20,
    paddingVertical: 19,
  },
  adminHeroGlow: {
    position: "absolute",
    width: 310,
    height: 310,
    borderRadius: 155,
    backgroundColor: "rgba(195, 159, 88, 0.11)",
    right: -100,
    top: -175,
  },
  adminHeroCopy: {
    flex: 1,
    zIndex: 1,
  },
  adminEyebrow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  adminEyebrowText: {
    color: "#D9C58F",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
  },
  adminHeroTitle: {
    color: "#F8F5EE",
    fontSize: 27,
    lineHeight: 33,
    fontWeight: "800",
    letterSpacing: -0.8,
    marginTop: 14,
  },
  adminHeroSubtitle: {
    maxWidth: 480,
    color: "#BDB9C7",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  adminRefreshButton: {
    minHeight: 37,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(242, 179, 61, 0.20)",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 11,
  },
  adminRefreshText: {
    color: "#2B2214",
    fontSize: 9,
    fontWeight: "700",
  },
  adminError: {
    borderWidth: 1,
    borderColor: "#F1D7D8",
    borderRadius: 13,
    backgroundColor: "#17131F",
    padding: 8,
  },
  adminErrorHint: {
    color: "#89766F",
    fontSize: 8,
    lineHeight: 13,
    paddingHorizontal: 4,
    paddingBottom: 3,
  },
  adminStats: {
    flexDirection: "row",
    gap: 11,
  },
  adminStatsMobile: {
    flexWrap: "wrap",
  },
  adminStat: {
    flex: 1,
    minWidth: 0,
    minHeight: 122,
    borderWidth: 1,
    borderColor: "#262033",
    borderRadius: 15,
    backgroundColor: "#17131F",
    padding: 14,
  },
  adminStatsMobileCard: {
    flexBasis: "47%",
    minHeight: 108,
  },
  adminStatTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  adminStatLabel: {
    color: "#8C88A1",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.9,
  },
  adminStatIcon: {
    width: 29,
    height: 29,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  adminStatValue: {
    color: "#302E40",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: -0.25,
    marginTop: 11,
  },
  adminStatDetail: {
    color: "#8C88A1",
    fontSize: 11,
    lineHeight: 17,
    marginTop: 4,
  },
  adminColumns: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  adminColumnsMobile: {
    flexDirection: "column",
  },
  adminPanel: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: "#262033",
    borderRadius: 16,
    backgroundColor: "#17131F",
    padding: 17,
  },
  adminPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 5,
  },
  adminPanelEyebrow: {
    color: "#9895A3",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 1,
  },
  adminPanelTitle: {
    color: "#333144",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: -0.2,
    marginTop: 5,
    marginBottom: 6,
  },
  adminLiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 20,
    backgroundColor: "#F1F7F3",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  adminLiveDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#34D399",
  },
  adminLiveDotOff: {
    backgroundColor: "#B98543",
  },
  adminLiveText: {
    color: "#648474",
    fontSize: 6,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  adminServiceRow: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderTopWidth: 1,
    borderTopColor: "#2B2539",
    paddingVertical: 9,
  },
  adminServiceIcon: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "#141017",
  },
  adminServiceIconActive: {
    backgroundColor: "#1F1A30",
  },
  adminServiceCopy: {
    flex: 1,
    minWidth: 0,
  },
  adminServiceTitle: {
    color: "#E9E4F4",
    fontSize: 9,
    fontWeight: "800",
  },
  adminServiceDetail: {
    color: "#9A97A5",
    fontSize: 7,
    lineHeight: 11,
    marginTop: 3,
  },
  adminServiceState: {
    color: "#A18B6B",
    fontSize: 6,
    fontWeight: "900",
    letterSpacing: 0.35,
    textAlign: "right",
  },
  adminServiceStateActive: {
    color: "#34D399",
  },
  adminJobGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  adminJobCount: {
    width: "48%",
    minHeight: 65,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#262033",
    borderRadius: 11,
    backgroundColor: "#14101C",
    paddingHorizontal: 11,
  },
  adminJobValue: {
    fontSize: 18,
    fontWeight: "800",
  },
  adminJobValue_success: {
    color: "#398D71",
  },
  adminJobValue_active: {
    color: "#A78BFA",
  },
  adminJobValue_waiting: {
    color: "#BE883D",
  },
  adminJobValue_failed: {
    color: "#BC6670",
  },
  adminJobLabel: {
    color: "#8C88A1",
    fontSize: 8,
    fontWeight: "600",
    marginTop: 3,
  },
  adminFootnote: {
    color: "#8C88A1",
    fontSize: 7,
    lineHeight: 12,
    marginTop: 11,
  },
  museAccountRow: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "#2B2539",
    paddingVertical: 8,
  },
  museAccountDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#34D399",
  },
  museAccountDotInactive: {
    backgroundColor: "#B5B2BE",
  },
  museAccountCopy: {
    flex: 1,
    minWidth: 0,
  },
  museAccountEmail: {
    color: "#E9E4F4",
    fontSize: 10,
    fontWeight: "800",
  },
  museAccountState: {
    color: "#8C88A1",
    fontSize: 8,
    marginTop: 3,
  },
  museAccountAction: {
    borderRadius: 8,
    backgroundColor: "#1F1A30",
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  museAccountActionText: {
    color: "#A78BFA",
    fontSize: 8,
    fontWeight: "800",
  },
  museAccountRemove: {
    backgroundColor: "#2B1619",
  },
  museAccountRemoveText: {
    color: "#F87171",
    fontSize: 8,
    fontWeight: "800",
  },
  museAccountForm: {
    gap: 8,
    marginTop: 11,
  },
  adminNextPanel: {
    minHeight: 112,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#363143",
    borderRadius: 16,
    backgroundColor: "#252333",
    paddingHorizontal: 17,
    paddingVertical: 15,
  },
  adminNextPanelMobile: {
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  adminNextIcon: {
    width: 38,
    height: 38,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#393447",
  },
  adminNextCopy: {
    flex: 1,
  },
  adminNextEyebrow: {
    color: "#D5BC7B",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  adminNextTitle: {
    color: "#F2EFF7",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 5,
  },
  adminNextText: {
    color: "#B1ADBC",
    fontSize: 8,
    lineHeight: 13,
    marginTop: 4,
  },
  adminSettingsButton: {
    minHeight: 33,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(242, 179, 61, 0.20)",
    borderRadius: 9,
    paddingHorizontal: 9,
  },
  adminSettingsButtonText: {
    color: "#8C88A1",
    fontSize: 8,
    fontWeight: "700",
  },
  integrationCard: {
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 17,
    backgroundColor: "#17131F",
    padding: 20,
  },
  integrationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  integrationBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  integrationLogo: {
    width: 43,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#7558E9",
  },
  integrationName: {
    color: "#F4F1FA",
    fontSize: 14,
    fontWeight: "800",
  },
  integrationType: {
    color: "#8C88A1",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.9,
    marginTop: 4,
  },
  connectedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 20,
    backgroundColor: "#122419",
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  connectedText: {
    color: "#43836D",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  integrationDescription: {
    color: "#8C88A1",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 18,
  },
  capabilityRows: {
    gap: 12,
    marginTop: 17,
  },
  capabilityRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
  },
  capabilityText: {
    flex: 1,
    color: "#B7B2C9",
    fontSize: 13,
    lineHeight: 20,
  },
  integrationFootnote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#332B4A",
    backgroundColor: "#1E1930",
    padding: 12,
    marginTop: 18,
  },
  integrationFootnoteText: {
    flex: 1,
    color: "#615B78",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  nextStepsCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 15,
    backgroundColor: "#17131F",
    padding: 16,
    marginTop: 13,
  },
  nextStepsIcon: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#EDF4FF",
  },
  nextStepsCopy: {
    flex: 1,
  },
  nextStepsTitle: {
    color: "#F4F1FA",
    fontSize: 14,
    fontWeight: "700",
  },
  nextStepsText: {
    color: "#82808F",
    fontSize: 12,
    lineHeight: 19,
    marginTop: 5,
  },
  settingsMuseButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderRadius: 14,
    backgroundColor: "#7C5CFF",
    marginTop: 13,
  },
  settingsMuseButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  emptyScreen: {
    minHeight: 470,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  emptyArtwork: {
    width: 86,
    height: 86,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 28,
    backgroundColor: "#1F1A30",
    marginBottom: 23,
  },
  emptyArtworkBack: {
    width: 54,
    height: 54,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#17131F",
  },
  emptyArtworkDot: {
    position: "absolute",
    width: 12,
    height: 12,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    borderRadius: 6,
    backgroundColor: "#EB8C9B",
    right: 12,
    top: 12,
  },
  emptyScreenTitle: {
    color: "#F4F1FA",
    fontSize: 21,
    fontWeight: "800",
    letterSpacing: -0.45,
    textAlign: "center",
    marginTop: 8,
  },
  emptyScreenText: {
    maxWidth: 340,
    color: "#8C88A1",
    fontSize: 11,
    lineHeight: 18,
    textAlign: "center",
    marginTop: 8,
  },
  emptyScreenButton: {
    minHeight: 39,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: 10,
    backgroundColor: "#7C5CFF",
    paddingHorizontal: 14,
    marginTop: 18,
  },
  emptyScreenButtonText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(25, 22, 39, 0.52)",
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  modalCard: {
    width: "100%",
    maxWidth: 510,
    maxHeight: "100%",
    borderRadius: 20,
    backgroundColor: "#17131F",
    padding: 22,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalIcon: {
    width: 43,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
  },
  modalClose: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "#141017",
  },
  modalTitle: {
    color: "#F4F1FA",
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.45,
    marginTop: 15,
  },
  modalSubtitle: {
    color: "#9894AE",
    fontSize: 10,
    lineHeight: 16,
    marginTop: 5,
  },
  modePill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 20,
    backgroundColor: "#F5F2FF",
    paddingHorizontal: 9,
    paddingVertical: 6,
    marginTop: 17,
  },
  modeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#795BEF",
  },
  modeDotVideo: {
    backgroundColor: "#D38C34",
  },
  modePillText: {
    color: "#6D56C0",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  inputLabel: {
    color: "#8C88A1",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.85,
    marginTop: 15,
    marginBottom: 7,
  },
  promptInput: {
    minHeight: 112,
    maxHeight: 175,
    borderWidth: 1,
    borderColor: "#E9E7EF",
    borderRadius: 12,
    color: "#F4F1FA",
    fontSize: 11,
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  promptMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  promptMetaText: {
    flex: 1,
    color: "#8C88A1",
    fontSize: 8,
  },
  connectionNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
    borderWidth: 1,
    borderColor: "#EBE6FA",
    borderRadius: 12,
    backgroundColor: "#151120",
    padding: 11,
    marginTop: 15,
  },
  connectionIcon: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#221B3A",
  },
  connectionCopy: {
    flex: 1,
  },
  connectionTitle: {
    color: "#454155",
    fontSize: 9,
    fontWeight: "800",
  },
  connectionText: {
    color: "#8C88A1",
    fontSize: 8,
    lineHeight: 13,
    marginTop: 4,
  },
  modalPrimaryButton: {
    minHeight: 41,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderRadius: 11,
    backgroundColor: "#7C5CFF",
    marginTop: 14,
  },
  modalPrimaryText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
  },
  featurePreview: {
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2B2539",
    borderRadius: 14,
    backgroundColor: "#FAF9FC",
    padding: 18,
    marginTop: 20,
  },
  previewIcon: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "#1F1A30",
  },
  featurePreviewTitle: {
    color: "#F4F1FA",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 12,
  },
  featurePreviewText: {
    color: "#9894AE",
    fontSize: 9,
    lineHeight: 15,
    textAlign: "center",
    marginTop: 6,
  },
  modalSecondaryButton: {
    minHeight: 39,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "#F1EEFC",
    marginTop: 14,
  },
  modalSecondaryText: {
    color: "#674DD3",
    fontSize: 10,
    fontWeight: "800",
  },
});
